### ISSUE TITLE
Time axis in segment review

### ISSUE THREAD

**Issue by VirgyLis** [smarsland/AviaNZ#11]
It could be a good idea to show time axis in the window for the segments review. At least could be better do not show time if the segments is too short because the two times overlap and is impossible to read them.

**Comment by jjuod** [comment]
Added some vertical spread for the time labels in 9cb9451cdca4dd6ea15cffeaef14c8571f9eeb0c . Not as much as I'd like because vertical zoom of the spectrogram is not constant, but should do for now.
