### ISSUE TITLE
Auto segment - duplicate segments

### ISSUE THREAD

**Issue by Nirosha201** [smarsland/AviaNZ#13]
Segmentation doesn't check for duplicates, e.g. if you accidentally click segment twice you will get duplicates.

**Comment by jjuod** [comment]
Fixed in 0bb720e21cb1a3c510717b739fb510b33b950604.
As in batch mode, single-species methods (wavelets, CC?) targeting species X now will wipe "X" and "X?" segments before proceeding. All other methods wipe all segments.
