### ISSUE TITLE
Minor issue with spectrogram parameters and spectrogram options

### ISSUE THREAD

**Issue by VirgyLis** [smarsland/AviaNZ#16]
When the user band-pass the filter the software changes the frequency band accordingly and this is fine.
The problem is that when you undo the denoising it doesn't restore the frequency band to the previous frequency band but to the frequency band of the file.
Of course, this is an issue with files with 'big' sample rate.

**Comment by jjuod** [comment]
Fixed in 37463e75d8dd06cc3a1fa73724e5f0af1af1efde
