### ISSUE TITLE
Single species review dialog bugs and testing

### ISSUE THREAD

**Issue by jjuod** [smarsland/AviaNZ#18]
Need to extensively test the new single species review, both through manual and batch modes. Some issues with not deleting segments were noticed.

**Comment by jjuod** [comment]
non-deletion issue was fixed in fact a problem with image update, fixed in fb8da9a27e3bcbe6c521abd440f089759f37933a . Essentially, do not use `update` for Macs, they need `repaint`.

**Comment by Nirosha201** [comment]
When there are two labels for a segment Species A, B, if the user choose that its not A (in single spp review)  then label B also get deleted. Ideally need to update the label without deleting the segment. Tested on manual mode.

**Comment by Nirosha201** [comment]
10 sec display for a segment is not helpful always, e.g. long (auto) segment having the species calling towards the end of it wont be visible. Display 10 sec and having the slide bar like in HumanReview [All] will be better.

**Comment by jjuod** [comment]
Fair point, we could do scrolling or different button sizes for larger segments. But the tradeoff is in complexity of the interface - we kinda want this mode to be "quick-confirm". I'd like to rethink this once we have improved filters and the segments match the sounds more precisely.

**Comment by jjuod** [comment]
> When there are two labels for a segment Species A, B, if the user choose that its not A (in single spp review) then label B also get deleted. Ideally need to update the label without deleting the segment. Tested on manual mode.

Fixed in bcefa04f994303e67c405fdf9e6a9c3b37c225c0

**Comment by jjuod** [comment]
A known issue is that single species review in manual mode only loads segments from the current page, even if `show all pages` is set to on in interface settings. Redrawing all the spectrograms however would introduce loading times, and most other options act on current page only, so we're not fixing it now.

**Comment by jjuod** [comment]
As of 7034c31ead0a17b09a34f26c870a8439d2d47279 , all-species review limited to current page only as well, so now (almost?) all manual mode interactions work on the current page. Closing.
