### ISSUE TITLE
listTopNodes

### ISSUE THREAD

**Issue by VirgyLis** [smarsland/AviaNZ#20]
We are calling this function 2 times in waveletSegmnet_train getting the same output.
1) in GenerateWPS: we call it for each file to have goodnodes list that we use to for update wf.tree
2) in gridsearch. For each file, we call it multiple times (1 time for each M and thr) to get the lists of nodesToTest and worstnodes.

I think that could be better to call this function just 1 time for each file storing these lists on a global variable.

It is not urgent and is not creating bugs.

My only concern is just computational costs.

**Comment by jjuod** [comment]
Finally got around to it in https://github.com/smarsland/AviaNZ/commit/6c79b7ee4be46e89362601a9dd1a90ede1abb902
