### ISSUE TITLE
Readonly option only partially work

### ISSUE THREAD

**Issue by Nirosha201** [smarsland/AviaNZ#21]
Appearance->Make readonly does not disable making segments.

**Comment by jjuod** [comment]
Yeah, we haven't been keeping track of this function when adding new things. We should consider what users want enabled in this mode, i.e.:
* selecting segments (for playback at least)?
* denoising?
* segmenting through menu?
* deleting existing segments or "remove all" menu option?
* reviewing segments?
For now, rewrote it to per my "vision" in 9e4229a443bf5788b5486c27d0ca2652227d2f1c

**Comment by Nirosha201** [comment]
Originally we added this option to get rid of accidentally creating/altering segments when the user just wants to read the files. No change to those other functionalities - above commit seems to work accordingly.
