### ISSUE TITLE
Windows: change interface setting

### ISSUE THREAD

**Issue by VirgyLis** [smarsland/AviaNZ#22]
On the window version, I have problems changing the interface settings.

It gives me this error:
Traceback (most recent call last):
  File "AviaNZ.py", line 4862, in changeSettings
KeyError: 'RequireNoiseData'

I have the same problem when I call AviaNZ.py from the prompt.
Traceback (most recent call last):
  File "AviaNZ.py", line 4878, in changeSettings
    {'name': 'Require noise data', 'type': 'bool', 'value': self.config['RequireNoiseData']},
KeyError: 'RequireNoiseData'

**Comment by jjuod** [comment]
Looks very much like an old config file. Try deleting `~\AppData\Roaming\AviaNZ\AviaNZconfig.txt` (or just the entire `Roaming\AviaNZ\` folder) and please reopen if it's still a problem. Ideally we should add a try-except to overwrite the config file if it looks old, but that's for a later release

**Comment by VirgyLis** [comment]
Done. Now it is working
