### ISSUE TITLE
Single species review

### ISSUE THREAD

**Issue by smarsland** [smarsland/AviaNZ#32]
The ideal single species review would have the same number of segments per page, without worrying about which file they came from. This is a bit of a pain to implement though.
A step towards that is only a "next" button that doesn't specify whether they come from the same file or not, to replace the current arrows.

**Comment by smarsland** [comment]
I've done the step. Please check with batch mode, since I haven't. I've hidden the previous arrow as well, since I think it was potentially confusing for users, since the difference between 'there are no previous pages in this file' and 'there are no previous pages' isn't necessarily clear.

**Comment by jjuod** [comment]
Looks good - there was a minor issue on my end with "yellow" marks, fixed now as of eb55d613494b381acd80af3eac43692348899e98 . Closing.
