### ISSUE TITLE
Batch process needs more status info towards the end 

### ISSUE THREAD

**Issue by Nirosha201** [smarsland/AviaNZ#39]
Current version of batch process computes the remaining time based on the processing time of the first file and does not count the time required to generate the excels at the end which could be a long time when processing a large data set. 
Users seems to think that the program crashes when it takes longer than it indicates in he status bar and no respond from the program. 
Solution would be either updating the the status bar (remaining time) or add a progress bar during the excel process.

**Comment by jjuod** [comment]
Status bar messages were there, but not updating properly - fixed that.
Can you try and see if this looks clear enough, or do we need to add a progress dialog?
(The excel export takes fraction of a second on the smaller datasets that I have, so can't check properly.)
