### ISSUE TITLE
Batch review need smooth transition to the next file

### ISSUE THREAD

**Issue by Nirosha201** [smarsland/AviaNZ#40]
Batch review has a noticeable waiting time before it opens up the segments from the next file, during this time what user can see is the parent window where user might try to click around when board of waiting and can mess around. 
So need to keep the user in the current review without distracting, maybe add a bridge to the next with a progress bar or something similar.

**Comment by jjuod** [comment]
Added a progress dialog in 5a9d063, should be clearer. Ideally, we could multi-thread this and load the next file in the background while the user is working on the current one. But I'm hesitant to do this without a good RAM check, to ensure that this will not fill up the memory.
