### ISSUE TITLE
Filter file naming should avoid reserved 'M' 

### ISSUE THREAD

**Issue by Nirosha201** [smarsland/AviaNZ#41]
"M" is reserved in AviaNZ - it is used to indicate manual labels. So it should be avoided when creating new filters.

**Comment by jjuod** [comment]
Fixed in https://github.com/smarsland/AviaNZ/commit/908dc323b6594d221bec303e8a4ab6b89aebc1b0, as well as the similar case for calltypes `"(Other)"`. Should also mention in the manual, although both names are weird enough to not be a common problem.
