### ISSUE TITLE
Improve testing result output

### ISSUE THREAD

**Issue by jjuod** [smarsland/AviaNZ#43]
Text file with output results should store more info, in particular:
* raw TP/FP/TN/FN values for each calltype
* precision for each calltype as it's arguably more important than recall?
* overall filter level stats

**Comment by VirgyLis** [comment]
I think that It should save as much as possible (e.g. all the stats we show in the previous window).
This is particularly useful if the user is doing experiments

**Comment by jjuod** [comment]
Everything that is on the testing pages is saved to the txt now. Feel free to reopen if any other info that should be stored comes to mind.
