### ISSUE TITLE
CNN wizard - ROCs should be moved to separate pages

### ISSUE THREAD

**Issue by jjuod** [smarsland/AviaNZ#62]
ROCs for each calltype in CNN training are currently placed in a single page, in a GridLayout. Given many calltypes, some will be permanently outside the screen area. Also, even with few calltypes, this requires dynamic scaling of plot sizes and text elements, and is difficult - I observe that every redraw (i.e. on clicking anywhere in the plot) slightly changes the plot area size.
Basically, the easiest solution probably is to reuse some code from filter training dialog, where we create the number of pages based on the filter, and then populate those with sort of fixed size plots.

**Comment by Nirosha201** [comment]
Thanks Julius, now this should be fixed as of https://github.com/smarsland/AviaNZ/commit/94178d6392f5ab10d2d0515e4fea9fa2e4f37853.
