### ISSUE TITLE
Error: config file corrupt

### ISSUE THREAD

**Issue by specificpossum** [smarsland/AviaNZ#69]
Hey I am having this issue when I try to open the program.
I am on Windows 10.
The command line opens up and starts the process, but then instead of the program coming up I get an error message
" ERROR: file C:\Users\Rachyl\AppData\Roaming\AviaNZ\AviaNZconfig.txt corrupt, delete it to restore default "

I found the AviaNZconfig text file and deleted it, but the same error message displayed when I then tried to open the program.

I then uninstalled and redownloaded the program but nothing has changed.

![image](https://user-images.githubusercontent.com/71426164/93427526-88d94000-f8f0-11ea-8408-4df21d6daaed.png)

**Comment by jjuod** [comment]
Hi,
thanks for reporting. Could you post any printout seen on the command prompt, and also attach the file `C:\Users\Rachyl\AppData\Roaming\AviaNZ\AviaNZconfig.txt`?

**Comment by specificpossum** [comment]
Thank you for the speedy reply
I uninstalled and reinstalled for a third time and this time it seems to be working. 
I have attached the text file and command prompt screen, anyway, but I guess it might not be useful now that it is working.
Closing this thread :)

![image](https://user-images.githubusercontent.com/71426164/93449332-30fa0380-f907-11ea-8e77-c1491a33776e.png)

[AviaNZconfig.txt](https://github.com/smarsland/AviaNZ/files/5237706/AviaNZconfig.txt)
