### ISSUE TITLE
Batch processing log and progress bar

### ISSUE THREAD

**Issue by Nirosha201** [smarsland/AviaNZ#76]
1. Currently, the log file stores the absolute path of the recordings. This is a problem when pausing and restarting the process later on, e.g. on a different OS, by default an external hard drive won't assign the same drive letter all the time on Win. Therefore, make the path relative.
2. The progress bar is useful and shows reasonable stats on a clean batch process. But it doesn't show meaningful stats when resuming a previous work.

**Comment by jjuod** [comment]
1. Fixed
2. Progress bar now shows total number of processed files (over all occasions)
3. also discovered that log file list got wiped after resumed analysis, which probably prevent resuming the same survey twice. Fixed
