### ISSUE TITLE
Setting frequency range above 24 kHz and setting show frequency guides to always doesn't change 24kHz limit

### ISSUE THREAD

**Issue by NeuroForLunch** [smarsland/AviaNZ#77]
I would like to set the high frequency to 196 kHz on the left side of the spectrogram but the levels do not respond to any changes always staying at 24 kHz.

**Comment by NeuroForLunch** [comment]
I found the solution using the menu item Appearance -> Change Spectrogram Parameters

**Comment by jjuod** [comment]
Cool, let us know if anything else comes up - we haven't used it much at such high sampling rates.
